[target.x86_64-pc-windows-msvc.vswhom-sys]
rustc-link-lib = ["ole32", "oleaut32"]

[target.x86_64-pc-windows-msvc.serde_core]

[target.x86_64-pc-windows-msvc.serde]

[target.x86_64-pc-windows-msvc.thiserror]

[target.x86_64-pc-windows-msvc.schemars]

[target.x86_64-pc-windows-msvc.selectors]

[target.x86_64-pc-windows-msvc.crossbeam-utils]

[target.x86_64-pc-windows-msvc.webview2-com-sys]
rustc-link-lib = ["ole32", "oleaut32"]

[target.x86_64-pc-windows-msvc.winapi-util]

[target.x86_64-pc-windows-msvc.parking_lot_core]

[target.x86_64-pc-windows-msvc.syn]

[target.x86_64-pc-windows-msvc.proc-macro2]
